# -*- mode: ruby -*-
# vi: set ft=ruby :

PUBLIC_SSHKEY_PATH = "~/.ssh/id_dsa.pub"

boxes = [
    {
        :name => "mongo-m1",
        :eth1 => "192.168.41.20",
        :mem => "2048",
        :cpu => "1"
    },
    {
        :name => "mongo-s1",
        :eth1 => "192.168.41.21",
        :mem => "2048",
        :cpu => "1"
    },
    {
        :name => "mongo-s2",
        :eth1 => "192.168.41.22",
        :mem => "2048",
        :cpu => "1"
    },
]

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network :private_network, ip: opts[:eth1]
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        # suggested speedup for network performance through faster name resolution
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        # suggested speedup by enabing multiple cpu cores, figured it would be by default
        v.customize ["modifyvm", :id, "--ioapic", "on"]
      end
      config.vm.provision "file", source: PUBLIC_SSHKEY_PATH, destination: "~/.ssh/authorized_keys"
    end
  end

end
